### ISSUE TITLE
Epic: Display An Avalanche Forecast

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast-app#2]
Reference/example forecast is [here](https://nwac.us/avalanche-forecast/#/forecast/7/111039). This epic tracks the view built off of the NAC API at `api.avalanche.org/v2/public/product/<id>`.

## User Stories
- [ ] A user can view the avalanche forecast for a zone of their choice
- [ ] A user can view the danger rating at all elevation bands today.
- [ ] A user can view the outlook for the danger rating at all elevation bands tomorrow.
- [x] A user can read the bottom line summary.
- [ ] A user can view iconography/a visual summary of all specific avalanche problems.
- [ ] A user can read avalanche problem specifics and view associated media.
- [ ] A user can read the forecast discussion and view associated media.
- [ ] A user can determine when the avalanche forecast is valid and if the currently-visible forecast has expired.

## Components
- [x] https://github.com/stevekuznetsov/avalanche-forecast-app/commit/d20cc8dcbc0a1534cbff2196a6a44f8d3b5e8074 the bottom line, with the highest danger for today displayed
- [ ] the danger rating for today, with the date, elevation bands and ratings labelled
- [ ] the danger rating for tomorrow, with the date and ratings labelled
- [ ] a row summary for avalanche problems, containing the type, rose, likelihood and size, which can be clicked to expand
- [ ] a detailed view for an avalanche problem, containing fully detailed/labeled views of everything in the summary, along with the discussion and media
- [ ] the forecast discussion
- [ ] a media reel

**Comment by stevekuznetsov** [comment]
Closing as this has moved to the project.
